#!/sbin/sh

# fixing CPU clocks to avoid issues in recovery
echo 1024000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq
echo 245000 > /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq

# trigger blue LED & button-backlight
echo '255' > /sys/class/leds/blue/brightness
echo '255' > /sys/class/leds/button-backlight/brightness

cat /dev/input/event1 > /dev/keycheck&
sleep 3

# turn of lights
echo '0' > /sys/class/leds/blue/brightness
echo '0' > /sys/class/leds/button-backlight/brightness

kill -9 $!
if [ -s /dev/keycheck -o -e /cache/recovery/boot ]
then
  echo 0 > /sys/class/android_usb/android0/enable
  echo 0fce > /sys/class/android_usb/android0/idVendor 
  echo 614f > /sys/class/android_usb/android0/idProduct
  echo "mass_storage,adb" > /sys/class/android_usb/android0/functions
  echo 1 > /sys/class/android_usb/android0/enable
  stop adbd

  rm /cache/recovery/boot
  mount -o remount,rw rootfs /
  umount -l /system
  umount -l /data
  umount -l /cache
  umount -l /sdcard
  umount -l /mnt/sdcard
  rm -r /sdcard
  rm -r /not/sdcard
  mkdir /sdcard
  mkdir /tmp
  rm /etc
  mkdir /etc
  cp /recovery.fstab /etc/recovery.fstab
  mount /dev/block/mmcblk0p1 /sdcard
  /sbin/recovery &
  /sbin/adbd_rec recovery
fi

#continue booting

